### ISSUE TITLE
Clean AppStore test resources before test run, too

### ISSUE THREAD

**Issue by selobosi** [eclipse/kuksa.integration#21]
When we had configured the Jenkins job to run the integration tests with the appstore of the appstacle cluster, the tests failed. The log of the appstore said that the user `test.user.username` and the AppCategory `test.app.category` could not be created because they existed already. The tests worked after I deleted these resources and the tests did also clean up the resources.

My guess is that the tests were once aborted and were not able to clean the resources they created. Hence all subsequent tests failed.

This problem could be solved if the tests cleaned the resources they create before and after the test run.

@alezor do you think this makes sense? Would you like to give this issue a try when you've got time? Thanks!

**Comment by alezor** [comment]
I am aware of the issue and will look into it!

**Comment by selobosi** [comment]
I have this impression that this was fixed in https://github.com/eclipse/kuksa.integration/commit/7b7ffd5827d628185d6576a432060cfd078298a2 . Is that right?

**Comment by alezor** [comment]
Yes, as for the Appstore tests, this should pose no further data overlap problems!
